permissions:
  id-token: write
  contents: read

name: anil_selfhosted

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: |
          if ! command -v unzip >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y unzip
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::835671582299:role/OIDC_github_role
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verify Terraform installation
        run: terraform version

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
